name: saaas-product

services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: myapp
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  php-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.php-api
    ports:
      - "8081:80"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/myapp

  rust-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.rust-api
    ports:
      - "8082:80"

  go-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.go-api
    ports:
      - "8083:80"

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:80"

  go-gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile.go-gateway
    ports:
      - "8080:80"
    depends_on:
      - php-api
      - go-api
      - rust-api
      - frontend
    environment:
      PHP_BACKEND_URL: http://php-api
      RUST_BACKEND_URL: http://rust-api
      GO_BACKEND_URL: http://go-api
      FRONTEND_URL: http://frontend

volumes:
  postgres_data:
